name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Grant execute for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Build Release AAB
        run: ./gradlew bundleRelease --no-daemon

      - name: Upload APK & AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: |
            app/build/outputs/**/*.aab
            app/build/outputs/**/*.apk
