name: Build SMP YBI App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create TWA using PWA Builder
      run: |
        # Install PWA Builder CLI
        npm install -g @pwabuilder/cli
        
        # Build APK from URL
        pwabuilder https://smpbhaktiinsanibogor.sch.id/app --platform android --output ./build
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: ./build/
        retention-days: 30
